language: python
python:
   - 2.7
install:
   - pip install nose coverage
script:
  - nosetests --with-coverage --cover-package=egginst,enstaller tests enstaller egginst
notifications:
  email:
    - davidc@enthought.com
    - cwebster@enthought.com
